### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chrisvidal** [initbiz/pdfgenerator-plugin#1]
Hi,
I'd need to generate some sort of PDF certification.
So I already have a PDF file with all necesary text, now I need to add the user full name and the current date I guess.
Is this possible to do with this plugin please?
It would be about modifying an existing PDF
thanks

**Comment by tomaszstrojny** [comment]
Hi @chrisvidal,

Sure, there are two options, but I'd recommend using the one from the docs. You just need to inject the data you want to the layout. In the layout you'll be able to use these variables as you do it in Twig.

Whole example taken directly from docs which shows how to do it in an AJAX handler:

```
    use Initbiz\Pdfgenerator\Classes\PdfGenerator;
    use Initbiz\ExamplePlugin\PdfLayouts\ExampleLayout;
    ...

    /*
    * OctoberCMS AJAX handler to download PDF
    */
    public function onDownloadPdf()
    {
        //Set data which will be injected to the layout
        $data = ['viewData' => 'Value of viewData'];

        $layout = new ExampleLayout($data);

        // Create a new PdfGenerator object with a filename and the layout as parameters
        $pdfGenerator = new PdfGenerator($filename, $layout);

        $pdfGenerator->generatePdf();

        return $pdfGenerator->downloadPdf();
    }
```

See docs for more specific info on how to do it.

Cheers,

Tomasz
